services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_serverpod
      POSTGRES_PASSWORD: "Vahi-IhLKipmoTJiVZWOsJOQ4ISbrjgT"
    volumes:
      - todo_serverpod_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "QdJwUWTr1LAqVqIE8GvQrf69p9AJMPu3"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_serverpod_test
      POSTGRES_PASSWORD: "BDMgMmfCROP6RISjDh2turA-kz8NtJo4"
    volumes:
      - todo_serverpod_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "psj6ZtpnS6xw8I9UJsHfALqjQ30X0SZs"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  todo_serverpod_data:
  todo_serverpod_test_data:
